version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - app-network
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.docker
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - redis_data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
